import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={cn(
          "min-h-screen font-sans antialiased grid place-items-center bg-secondary",
          fontSans.variable
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="max-w-md w-full mx-auto border border-border shadow-xl rounded-2xl h-svh relative max-h-[840px] overflow-clip">
              <main className="h-[min(calc(100svh-20px),820px)] bg-background overflow-y-auto pb-4">
                {children}
              </main>
              <nav className="bg-secondary rounded-t-md overflow-hidden absolute bottom-0 left-0 right-0 h-">
                <Navbar />
              </nav>
            </div>
          </ThemeProvider>
        </body>
    </html>
  );
}
